name: main_workflow
on:
  push:
    branches:
      - "nodejs_nodeversions_job"
jobs:
  linter-execution:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - node: 10
          - node: 12
    steps:
      - uses: actions/checkout@v2
      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: nodejs_nodeversions_job
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: /
          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.json
          VALIDATE_JAVASCRIPT_ES: true

  test-execution:
    needs: linter-execution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - run: npm install -D
      - run: npm run test
