name: main_workflow
on:
  push:
    branches:
      - "nodejs_jest_job"
jobs:
  linter-execution:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: nodejs_jest_job
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: /
          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.json
          VALIDATE_JAVASCRIPT_ES: true

  test-execution:
    needs: linter-execution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install -D
      - run: npm run test
        id: jest
        continue-on-error: true
      - name: Check on failures
        if: steps.jest.outcome  != 'success'
        run: echo "Error en el test"
        # uses: dawidd6/action-send-mail@v3
        # with:
        #   server_address: smtp.gmail.com
        #   server_port: 465
        #   secure: true
        #   username: ${{secrets.MAIL_USERNAME}}
        #   password: ${{secrets.MAIL_PASSWORD}}
        #   subject: Error jest
        #   to: sergimicoortiz@gmail.com
        #   from: sergimico24@gmail.com
        #   body: Error en el job de jest