name: main_workflow
on:
  push:
    branches:
      - "nodejs_environment_job"
jobs:
  linter-execution:
    strategy:
      matrix:
        include:
          - node: 10
          - node: 12
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: nodejs_environment_job
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: /
          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.json
          VALIDATE_JAVASCRIPT_ES: true

  test-execution:
    needs: linter-execution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install -D
      - run: npm run test

  environment_test_execution:
    env:
      DESTINATION_PERSON: 2DAW
    needs: test-execution
    runs-on: ubuntu-latest
    steps:
      - uses: adeloyedeji/github-actions-hello@v1.0
        env:
          who-to-greet: ${{DESTINATION_PERSON}}
